# Generated by Django 5.0 on 2024-02-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeassign',
            name='employee',
        ),
        migrations.AddField(
            model_name='employeeassign',
            name='employee',
            field=models.ManyToManyField(blank=True, to='Tasks.employee'),
        ),
    ]
